/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.46
 * Generated at: 2022-05-31 12:09:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.case03;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class exam_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(10);
    _jspx_dependants.put("/WEB-INF/views/case03/exam_list.jspf", Long.valueOf(1652012730845L));
    _jspx_dependants.put("jar:file:/C:/Users/shion/Desktop/java_Spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/springmvc/WEB-INF/lib/javax.servlet.jsp.jstl-1.2.4.jar!/META-INF/fmt.tld", Long.valueOf(1420527028000L));
    _jspx_dependants.put("/WEB-INF/views/case03/include/header.jspf", Long.valueOf(1645867862000L));
    _jspx_dependants.put("/WEB-INF/views/case03/exam_form.jspf", Long.valueOf(1652012681164L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.3.29.RELEASE.jar", Long.valueOf(1644731966281L));
    _jspx_dependants.put("/WEB-INF/lib/javax.servlet.jsp.jstl-1.2.4.jar", Long.valueOf(1644731960697L));
    _jspx_dependants.put("jar:file:/C:/Users/shion/Desktop/java_Spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/springmvc/WEB-INF/lib/javax.servlet.jsp.jstl-1.2.4.jar!/META-INF/fn.tld", Long.valueOf(1420527028000L));
    _jspx_dependants.put("jar:file:/C:/Users/shion/Desktop/java_Spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/springmvc/WEB-INF/lib/spring-webmvc-4.3.29.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1600137476000L));
    _jspx_dependants.put("/WEB-INF/views/case03/include/footer.jspf", Long.valueOf(1645867862000L));
    _jspx_dependants.put("jar:file:/C:/Users/shion/Desktop/java_Spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/springmvc/WEB-INF/lib/javax.servlet.jsp.jstl-1.2.4.jar!/META-INF/c.tld", Long.valueOf(1420527028000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspform_005fform_0026_005fmodelAttribute_005fmethod_005fclass_005faction;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspform_005finput_0026_005fpath_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspform_005fselect_0026_005fpath;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspform_005foption_0026_005fvalue;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspform_005foptions_0026_005fitems_005fitemValue_005fitemLabel_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspform_005finput_0026_005ftype_005fpath_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspform_005fcheckbox_0026_005fvalue_005fpath_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspform_005fradiobutton_0026_005fvalue_005fpath_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspform_005ftextarea_0026_005fpath_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fspform_005fform_0026_005fmodelAttribute_005fmethod_005fclass_005faction = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fspform_005finput_0026_005fpath_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fspform_005fselect_0026_005fpath = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fspform_005foption_0026_005fvalue = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fspform_005foptions_0026_005fitems_005fitemValue_005fitemLabel_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fspform_005finput_0026_005ftype_005fpath_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fspform_005fcheckbox_0026_005fvalue_005fpath_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fspform_005fradiobutton_0026_005fvalue_005fpath_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fspform_005ftextarea_0026_005fpath_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fspform_005fform_0026_005fmodelAttribute_005fmethod_005fclass_005faction.release();
    _005fjspx_005ftagPool_005fspform_005finput_0026_005fpath_005fnobody.release();
    _005fjspx_005ftagPool_005fspform_005fselect_0026_005fpath.release();
    _005fjspx_005ftagPool_005fspform_005foption_0026_005fvalue.release();
    _005fjspx_005ftagPool_005fspform_005foptions_0026_005fitems_005fitemValue_005fitemLabel_005fnobody.release();
    _005fjspx_005ftagPool_005fspform_005finput_0026_005ftype_005fpath_005fnobody.release();
    _005fjspx_005ftagPool_005fspform_005fcheckbox_0026_005fvalue_005fpath_005fnobody.release();
    _005fjspx_005ftagPool_005fspform_005fradiobutton_0026_005fvalue_005fpath_005fnobody.release();
    _005fjspx_005ftagPool_005fspform_005ftextarea_0026_005fpath_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("	");
      out.write("\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"https://unpkg.com/purecss@2.0.6/build/pure-min.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/exam.css\">\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/exam.js\"></script>	\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Exam From</title>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body class=\"exambody\">\n");
      out.write("	<table class=\"examtable\">\n");
      out.write("		<tr>\n");
      out.write("			<!-- Exam Form -->\n");
      out.write("			<td valign=\"top\">\n");
      out.write("				");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      //  spform:form
      org.springframework.web.servlet.tags.form.FormTag _jspx_th_spform_005fform_005f0 = (org.springframework.web.servlet.tags.form.FormTag) _005fjspx_005ftagPool_005fspform_005fform_0026_005fmodelAttribute_005fmethod_005fclass_005faction.get(org.springframework.web.servlet.tags.form.FormTag.class);
      boolean _jspx_th_spform_005fform_005f0_reused = false;
      try {
        _jspx_th_spform_005fform_005f0.setPageContext(_jspx_page_context);
        _jspx_th_spform_005fform_005f0.setParent(null);
        // /WEB-INF/views/case03/exam_form.jspf(8,0) null
        _jspx_th_spform_005fform_005f0.setDynamicAttribute(null, "class", "pure-form");
        // /WEB-INF/views/case03/exam_form.jspf(8,0) name = method type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_spform_005fform_005f0.setMethod("post");
        // /WEB-INF/views/case03/exam_form.jspf(8,0) name = modelAttribute type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_spform_005fform_005f0.setModelAttribute("exam");
        // /WEB-INF/views/case03/exam_form.jspf(8,0) name = action type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_spform_005fform_005f0.setAction((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }/mvc/case03/exam/", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        int[] _jspx_push_body_count_spform_005fform_005f0 = new int[] { 0 };
        try {
          int _jspx_eval_spform_005fform_005f0 = _jspx_th_spform_005fform_005f0.doStartTag();
          if (_jspx_eval_spform_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            do {
              out.write("\n");
              out.write("	<fieldset>\n");
              out.write("		<legend>Exam Form ");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ index }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("</legend>\n");
              out.write("		<input type=\"hidden\" id=\"_method\" name=\"_method\" value=\"");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ _method }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("\">\n");
              out.write("		學號：\n");
              out.write("		");
              if (_jspx_meth_spform_005finput_005f0(_jspx_th_spform_005fform_005f0, _jspx_page_context, _jspx_push_body_count_spform_005fform_005f0))
                return;
              out.write("\n");
              out.write("		<p />\n");
              out.write("		科目：\n");
              out.write("		");
              //  spform:select
              org.springframework.web.servlet.tags.form.SelectTag _jspx_th_spform_005fselect_005f0 = (org.springframework.web.servlet.tags.form.SelectTag) _005fjspx_005ftagPool_005fspform_005fselect_0026_005fpath.get(org.springframework.web.servlet.tags.form.SelectTag.class);
              boolean _jspx_th_spform_005fselect_005f0_reused = false;
              try {
                _jspx_th_spform_005fselect_005f0.setPageContext(_jspx_page_context);
                _jspx_th_spform_005fselect_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spform_005fform_005f0);
                // /WEB-INF/views/case03/exam_form.jspf(17,2) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_spform_005fselect_005f0.setPath("examId");
                int[] _jspx_push_body_count_spform_005fselect_005f0 = new int[] { 0 };
                try {
                  int _jspx_eval_spform_005fselect_005f0 = _jspx_th_spform_005fselect_005f0.doStartTag();
                  if (_jspx_eval_spform_005fselect_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                    do {
                      out.write("\n");
                      out.write("			");
                      //  spform:option
                      org.springframework.web.servlet.tags.form.OptionTag _jspx_th_spform_005foption_005f0 = (org.springframework.web.servlet.tags.form.OptionTag) _005fjspx_005ftagPool_005fspform_005foption_0026_005fvalue.get(org.springframework.web.servlet.tags.form.OptionTag.class);
                      boolean _jspx_th_spform_005foption_005f0_reused = false;
                      try {
                        _jspx_th_spform_005foption_005f0.setPageContext(_jspx_page_context);
                        _jspx_th_spform_005foption_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spform_005fselect_005f0);
                        // /WEB-INF/views/case03/exam_form.jspf(18,3) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                        _jspx_th_spform_005foption_005f0.setValue("");
                        int[] _jspx_push_body_count_spform_005foption_005f0 = new int[] { 0 };
                        try {
                          int _jspx_eval_spform_005foption_005f0 = _jspx_th_spform_005foption_005f0.doStartTag();
                          if (_jspx_eval_spform_005foption_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                            java.lang.Object value = null;
                            java.lang.String displayValue = null;
                            if (_jspx_eval_spform_005foption_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                              _jspx_push_body_count_spform_005foption_005f0[0]++;
                              out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_spform_005foption_005f0);
                            }
                            value = (java.lang.Object) _jspx_page_context.findAttribute("value");
                            displayValue = (java.lang.String) _jspx_page_context.findAttribute("displayValue");
                            do {
                              out.write('請');
                              out.write('選');
                              out.write('擇');
                              int evalDoAfterBody = _jspx_th_spform_005foption_005f0.doAfterBody();
                              value = (java.lang.Object) _jspx_page_context.findAttribute("value");
                              displayValue = (java.lang.String) _jspx_page_context.findAttribute("displayValue");
                              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                              break;
                            } while (true);
                            if (_jspx_eval_spform_005foption_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                              out = _jspx_page_context.popBody();
                              _jspx_push_body_count_spform_005foption_005f0[0]--;
                            }
                          }
                          if (_jspx_th_spform_005foption_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                            return;
                          }
                        } catch (java.lang.Throwable _jspx_exception) {
                          while (_jspx_push_body_count_spform_005foption_005f0[0]-- > 0)
                            out = _jspx_page_context.popBody();
                          _jspx_th_spform_005foption_005f0.doCatch(_jspx_exception);
                        } finally {
                          _jspx_th_spform_005foption_005f0.doFinally();
                        }
                        _005fjspx_005ftagPool_005fspform_005foption_0026_005fvalue.reuse(_jspx_th_spform_005foption_005f0);
                        _jspx_th_spform_005foption_005f0_reused = true;
                      } finally {
                        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spform_005foption_005f0, _jsp_getInstanceManager(), _jspx_th_spform_005foption_005f0_reused);
                      }
                      out.write("\n");
                      out.write("			");
                      if (_jspx_meth_spform_005foptions_005f0(_jspx_th_spform_005fselect_005f0, _jspx_page_context, _jspx_push_body_count_spform_005fselect_005f0))
                        return;
                      out.write('\n');
                      out.write('	');
                      out.write('	');
                      int evalDoAfterBody = _jspx_th_spform_005fselect_005f0.doAfterBody();
                      if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                        break;
                    } while (true);
                  }
                  if (_jspx_th_spform_005fselect_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                    return;
                  }
                } catch (java.lang.Throwable _jspx_exception) {
                  while (_jspx_push_body_count_spform_005fselect_005f0[0]-- > 0)
                    out = _jspx_page_context.popBody();
                  _jspx_th_spform_005fselect_005f0.doCatch(_jspx_exception);
                } finally {
                  _jspx_th_spform_005fselect_005f0.doFinally();
                }
                _005fjspx_005ftagPool_005fspform_005fselect_0026_005fpath.reuse(_jspx_th_spform_005fselect_005f0);
                _jspx_th_spform_005fselect_005f0_reused = true;
              } finally {
                org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spform_005fselect_005f0, _jsp_getInstanceManager(), _jspx_th_spform_005fselect_005f0_reused);
              }
              out.write("\n");
              out.write("		<p />\n");
              out.write("		日期：\n");
              out.write("		");
              if (_jspx_meth_spform_005finput_005f1(_jspx_th_spform_005fform_005f0, _jspx_page_context, _jspx_push_body_count_spform_005fform_005f0))
                return;
              out.write("\n");
              out.write("		<p />\n");
              out.write("		時段：\n");
              out.write("		<!-- Homework 時段改成 spform:checkboxes -->\n");
              out.write("		");
              if (_jspx_meth_spform_005fcheckbox_005f0(_jspx_th_spform_005fform_005f0, _jspx_page_context, _jspx_push_body_count_spform_005fform_005f0))
                return;
              out.write("\n");
              out.write("		上午(A)\n");
              out.write("		");
              if (_jspx_meth_spform_005fcheckbox_005f1(_jspx_th_spform_005fform_005f0, _jspx_page_context, _jspx_push_body_count_spform_005fform_005f0))
                return;
              out.write("\n");
              out.write("		下午(B)\n");
              out.write("		");
              if (_jspx_meth_spform_005fcheckbox_005f2(_jspx_th_spform_005fform_005f0, _jspx_page_context, _jspx_push_body_count_spform_005fform_005f0))
                return;
              out.write("\n");
              out.write("		晚上(C)\n");
              out.write("		<p />\n");
              out.write("		繳費：\n");
              out.write("		<!-- Homework 繳費 spform:radiobuttons -->\n");
              out.write("		");
              if (_jspx_meth_spform_005fradiobutton_005f0(_jspx_th_spform_005fform_005f0, _jspx_page_context, _jspx_push_body_count_spform_005fform_005f0))
                return;
              out.write("\n");
              out.write("		已繳\n");
              out.write("		");
              if (_jspx_meth_spform_005fradiobutton_005f1(_jspx_th_spform_005fform_005f0, _jspx_page_context, _jspx_push_body_count_spform_005fform_005f0))
                return;
              out.write("\n");
              out.write("		未繳\n");
              out.write("		<p />\n");
              out.write("		備註：\n");
              out.write("		");
              if (_jspx_meth_spform_005ftextarea_005f0(_jspx_th_spform_005fform_005f0, _jspx_page_context, _jspx_push_body_count_spform_005fform_005f0))
                return;
              out.write("\n");
              out.write("		<p />\n");
              out.write("		<button type=\"submit\" class=\"pure-button pure-button-primary\" ");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ _method == 'POST'?'':'disabled' }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write(" >新增</button>\n");
              out.write("		<button type=\"button\" class=\"pure-button pure-button-primary\" ");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ _method == 'PUT'?'':'disabled' }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write(" onclick=\"updateExam(");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ index }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write(")\">修改</button>\n");
              out.write("		<button type=\"button\" class=\"pure-button pure-button-primary\" ");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ _method == 'PUT'?'':'disabled' }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write(" onclick=\"deleteExam(");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ index }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write(")\">刪除</button>\n");
              out.write("	</fieldset>\n");
              int evalDoAfterBody = _jspx_th_spform_005fform_005f0.doAfterBody();
              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
          }
          if (_jspx_th_spform_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            return;
          }
        } catch (java.lang.Throwable _jspx_exception) {
          while (_jspx_push_body_count_spform_005fform_005f0[0]-- > 0)
            out = _jspx_page_context.popBody();
          _jspx_th_spform_005fform_005f0.doCatch(_jspx_exception);
        } finally {
          _jspx_th_spform_005fform_005f0.doFinally();
        }
        _005fjspx_005ftagPool_005fspform_005fform_0026_005fmodelAttribute_005fmethod_005fclass_005faction.reuse(_jspx_th_spform_005fform_005f0);
        _jspx_th_spform_005fform_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spform_005fform_005f0, _jsp_getInstanceManager(), _jspx_th_spform_005fform_005f0_reused);
      }
      out.write("\n");
      out.write("			</td>\n");
      out.write("			<!-- Exam List -->\n");
      out.write("			<td valign=\"top\">\n");
      out.write("				");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<form class=\"pure-form\">\n");
      out.write("	<fieldset>\n");
      out.write("		<legend>Exam List</legend>\n");
      out.write("		<table class=\"pure-table pure-table-bordered\">\n");
      out.write("			<thead>\n");
      out.write("				<tr>\n");
      out.write("					<th>index</th>\n");
      out.write("					<th>學員學號</th>\n");
      out.write("					<th>考試科目</th>\n");
      out.write("					<th>考試日期</th>\n");
      out.write("					<th>考試時段</th>\n");
      out.write("					<th>繳費狀況</th>\n");
      out.write("					<th>其他備註</th>\n");
      out.write("				</tr>\n");
      out.write("			</thead>\n");
      out.write("			<tbody>\n");
      out.write("				");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("			</tbody>\n");
      out.write("		</table>\n");
      out.write("	</fieldset>\n");
      out.write("</form>");
      out.write("\n");
      out.write("			</td>\n");
      out.write("		</tr>\n");
      out.write("	</table>\n");
      out.write("	");
      out.write("\n");
      out.write("\n");
      out.write("<br /><br />\n");
      out.write("<center>\n");
      out.write("	Lab：Exam 考試註冊 202202/20\n");
      out.write("</center>");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_spform_005finput_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_spform_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_spform_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spform:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_spform_005finput_005f0 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fspform_005finput_0026_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    boolean _jspx_th_spform_005finput_005f0_reused = false;
    try {
      _jspx_th_spform_005finput_005f0.setPageContext(_jspx_page_context);
      _jspx_th_spform_005finput_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spform_005fform_005f0);
      // /WEB-INF/views/case03/exam_form.jspf(14,2) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spform_005finput_005f0.setPath("studentId");
      int[] _jspx_push_body_count_spform_005finput_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_spform_005finput_005f0 = _jspx_th_spform_005finput_005f0.doStartTag();
        if (_jspx_th_spform_005finput_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spform_005finput_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spform_005finput_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spform_005finput_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fspform_005finput_0026_005fpath_005fnobody.reuse(_jspx_th_spform_005finput_005f0);
      _jspx_th_spform_005finput_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spform_005finput_005f0, _jsp_getInstanceManager(), _jspx_th_spform_005finput_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spform_005foptions_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_spform_005fselect_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_spform_005fselect_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spform:options
    org.springframework.web.servlet.tags.form.OptionsTag _jspx_th_spform_005foptions_005f0 = (org.springframework.web.servlet.tags.form.OptionsTag) _005fjspx_005ftagPool_005fspform_005foptions_0026_005fitems_005fitemValue_005fitemLabel_005fnobody.get(org.springframework.web.servlet.tags.form.OptionsTag.class);
    boolean _jspx_th_spform_005foptions_005f0_reused = false;
    try {
      _jspx_th_spform_005foptions_005f0.setPageContext(_jspx_page_context);
      _jspx_th_spform_005foptions_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spform_005fselect_005f0);
      // /WEB-INF/views/case03/exam_form.jspf(19,3) name = items type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spform_005foptions_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ examSubjects }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/views/case03/exam_form.jspf(19,3) name = itemValue type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spform_005foptions_005f0.setItemValue("id");
      // /WEB-INF/views/case03/exam_form.jspf(19,3) name = itemLabel type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spform_005foptions_005f0.setItemLabel("name");
      int[] _jspx_push_body_count_spform_005foptions_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_spform_005foptions_005f0 = _jspx_th_spform_005foptions_005f0.doStartTag();
        if (_jspx_th_spform_005foptions_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spform_005foptions_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spform_005foptions_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spform_005foptions_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fspform_005foptions_0026_005fitems_005fitemValue_005fitemLabel_005fnobody.reuse(_jspx_th_spform_005foptions_005f0);
      _jspx_th_spform_005foptions_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spform_005foptions_005f0, _jsp_getInstanceManager(), _jspx_th_spform_005foptions_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spform_005finput_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_spform_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_spform_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spform:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_spform_005finput_005f1 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fspform_005finput_0026_005ftype_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    boolean _jspx_th_spform_005finput_005f1_reused = false;
    try {
      _jspx_th_spform_005finput_005f1.setPageContext(_jspx_page_context);
      _jspx_th_spform_005finput_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spform_005fform_005f0);
      // /WEB-INF/views/case03/exam_form.jspf(23,2) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spform_005finput_005f1.setPath("examDate");
      // /WEB-INF/views/case03/exam_form.jspf(23,2) null
      _jspx_th_spform_005finput_005f1.setDynamicAttribute(null, "type", "date");
      int[] _jspx_push_body_count_spform_005finput_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_spform_005finput_005f1 = _jspx_th_spform_005finput_005f1.doStartTag();
        if (_jspx_th_spform_005finput_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spform_005finput_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spform_005finput_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spform_005finput_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fspform_005finput_0026_005ftype_005fpath_005fnobody.reuse(_jspx_th_spform_005finput_005f1);
      _jspx_th_spform_005finput_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spform_005finput_005f1, _jsp_getInstanceManager(), _jspx_th_spform_005finput_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spform_005fcheckbox_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_spform_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_spform_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spform:checkbox
    org.springframework.web.servlet.tags.form.CheckboxTag _jspx_th_spform_005fcheckbox_005f0 = (org.springframework.web.servlet.tags.form.CheckboxTag) _005fjspx_005ftagPool_005fspform_005fcheckbox_0026_005fvalue_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.CheckboxTag.class);
    boolean _jspx_th_spform_005fcheckbox_005f0_reused = false;
    try {
      _jspx_th_spform_005fcheckbox_005f0.setPageContext(_jspx_page_context);
      _jspx_th_spform_005fcheckbox_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spform_005fform_005f0);
      // /WEB-INF/views/case03/exam_form.jspf(27,2) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spform_005fcheckbox_005f0.setPath("examSlot");
      // /WEB-INF/views/case03/exam_form.jspf(27,2) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spform_005fcheckbox_005f0.setValue("A");
      int[] _jspx_push_body_count_spform_005fcheckbox_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_spform_005fcheckbox_005f0 = _jspx_th_spform_005fcheckbox_005f0.doStartTag();
        if (_jspx_th_spform_005fcheckbox_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spform_005fcheckbox_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spform_005fcheckbox_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spform_005fcheckbox_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fspform_005fcheckbox_0026_005fvalue_005fpath_005fnobody.reuse(_jspx_th_spform_005fcheckbox_005f0);
      _jspx_th_spform_005fcheckbox_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spform_005fcheckbox_005f0, _jsp_getInstanceManager(), _jspx_th_spform_005fcheckbox_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spform_005fcheckbox_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_spform_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_spform_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spform:checkbox
    org.springframework.web.servlet.tags.form.CheckboxTag _jspx_th_spform_005fcheckbox_005f1 = (org.springframework.web.servlet.tags.form.CheckboxTag) _005fjspx_005ftagPool_005fspform_005fcheckbox_0026_005fvalue_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.CheckboxTag.class);
    boolean _jspx_th_spform_005fcheckbox_005f1_reused = false;
    try {
      _jspx_th_spform_005fcheckbox_005f1.setPageContext(_jspx_page_context);
      _jspx_th_spform_005fcheckbox_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spform_005fform_005f0);
      // /WEB-INF/views/case03/exam_form.jspf(29,2) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spform_005fcheckbox_005f1.setPath("examSlot");
      // /WEB-INF/views/case03/exam_form.jspf(29,2) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spform_005fcheckbox_005f1.setValue("B");
      int[] _jspx_push_body_count_spform_005fcheckbox_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_spform_005fcheckbox_005f1 = _jspx_th_spform_005fcheckbox_005f1.doStartTag();
        if (_jspx_th_spform_005fcheckbox_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spform_005fcheckbox_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spform_005fcheckbox_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spform_005fcheckbox_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fspform_005fcheckbox_0026_005fvalue_005fpath_005fnobody.reuse(_jspx_th_spform_005fcheckbox_005f1);
      _jspx_th_spform_005fcheckbox_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spform_005fcheckbox_005f1, _jsp_getInstanceManager(), _jspx_th_spform_005fcheckbox_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spform_005fcheckbox_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_spform_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_spform_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spform:checkbox
    org.springframework.web.servlet.tags.form.CheckboxTag _jspx_th_spform_005fcheckbox_005f2 = (org.springframework.web.servlet.tags.form.CheckboxTag) _005fjspx_005ftagPool_005fspform_005fcheckbox_0026_005fvalue_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.CheckboxTag.class);
    boolean _jspx_th_spform_005fcheckbox_005f2_reused = false;
    try {
      _jspx_th_spform_005fcheckbox_005f2.setPageContext(_jspx_page_context);
      _jspx_th_spform_005fcheckbox_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spform_005fform_005f0);
      // /WEB-INF/views/case03/exam_form.jspf(31,2) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spform_005fcheckbox_005f2.setPath("examSlot");
      // /WEB-INF/views/case03/exam_form.jspf(31,2) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spform_005fcheckbox_005f2.setValue("C");
      int[] _jspx_push_body_count_spform_005fcheckbox_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_spform_005fcheckbox_005f2 = _jspx_th_spform_005fcheckbox_005f2.doStartTag();
        if (_jspx_th_spform_005fcheckbox_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spform_005fcheckbox_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spform_005fcheckbox_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spform_005fcheckbox_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fspform_005fcheckbox_0026_005fvalue_005fpath_005fnobody.reuse(_jspx_th_spform_005fcheckbox_005f2);
      _jspx_th_spform_005fcheckbox_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spform_005fcheckbox_005f2, _jsp_getInstanceManager(), _jspx_th_spform_005fcheckbox_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spform_005fradiobutton_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_spform_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_spform_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spform:radiobutton
    org.springframework.web.servlet.tags.form.RadioButtonTag _jspx_th_spform_005fradiobutton_005f0 = (org.springframework.web.servlet.tags.form.RadioButtonTag) _005fjspx_005ftagPool_005fspform_005fradiobutton_0026_005fvalue_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.RadioButtonTag.class);
    boolean _jspx_th_spform_005fradiobutton_005f0_reused = false;
    try {
      _jspx_th_spform_005fradiobutton_005f0.setPageContext(_jspx_page_context);
      _jspx_th_spform_005fradiobutton_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spform_005fform_005f0);
      // /WEB-INF/views/case03/exam_form.jspf(36,2) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spform_005fradiobutton_005f0.setPath("examPay");
      // /WEB-INF/views/case03/exam_form.jspf(36,2) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spform_005fradiobutton_005f0.setValue("true");
      int[] _jspx_push_body_count_spform_005fradiobutton_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_spform_005fradiobutton_005f0 = _jspx_th_spform_005fradiobutton_005f0.doStartTag();
        if (_jspx_th_spform_005fradiobutton_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spform_005fradiobutton_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spform_005fradiobutton_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spform_005fradiobutton_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fspform_005fradiobutton_0026_005fvalue_005fpath_005fnobody.reuse(_jspx_th_spform_005fradiobutton_005f0);
      _jspx_th_spform_005fradiobutton_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spform_005fradiobutton_005f0, _jsp_getInstanceManager(), _jspx_th_spform_005fradiobutton_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spform_005fradiobutton_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_spform_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_spform_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spform:radiobutton
    org.springframework.web.servlet.tags.form.RadioButtonTag _jspx_th_spform_005fradiobutton_005f1 = (org.springframework.web.servlet.tags.form.RadioButtonTag) _005fjspx_005ftagPool_005fspform_005fradiobutton_0026_005fvalue_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.RadioButtonTag.class);
    boolean _jspx_th_spform_005fradiobutton_005f1_reused = false;
    try {
      _jspx_th_spform_005fradiobutton_005f1.setPageContext(_jspx_page_context);
      _jspx_th_spform_005fradiobutton_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spform_005fform_005f0);
      // /WEB-INF/views/case03/exam_form.jspf(38,2) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spform_005fradiobutton_005f1.setPath("examPay");
      // /WEB-INF/views/case03/exam_form.jspf(38,2) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spform_005fradiobutton_005f1.setValue("false");
      int[] _jspx_push_body_count_spform_005fradiobutton_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_spform_005fradiobutton_005f1 = _jspx_th_spform_005fradiobutton_005f1.doStartTag();
        if (_jspx_th_spform_005fradiobutton_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spform_005fradiobutton_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spform_005fradiobutton_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spform_005fradiobutton_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fspform_005fradiobutton_0026_005fvalue_005fpath_005fnobody.reuse(_jspx_th_spform_005fradiobutton_005f1);
      _jspx_th_spform_005fradiobutton_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spform_005fradiobutton_005f1, _jsp_getInstanceManager(), _jspx_th_spform_005fradiobutton_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spform_005ftextarea_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_spform_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_spform_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spform:textarea
    org.springframework.web.servlet.tags.form.TextareaTag _jspx_th_spform_005ftextarea_005f0 = (org.springframework.web.servlet.tags.form.TextareaTag) _005fjspx_005ftagPool_005fspform_005ftextarea_0026_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.TextareaTag.class);
    boolean _jspx_th_spform_005ftextarea_005f0_reused = false;
    try {
      _jspx_th_spform_005ftextarea_005f0.setPageContext(_jspx_page_context);
      _jspx_th_spform_005ftextarea_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spform_005fform_005f0);
      // /WEB-INF/views/case03/exam_form.jspf(42,2) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spform_005ftextarea_005f0.setPath("examNote");
      int[] _jspx_push_body_count_spform_005ftextarea_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_spform_005ftextarea_005f0 = _jspx_th_spform_005ftextarea_005f0.doStartTag();
        if (_jspx_th_spform_005ftextarea_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spform_005ftextarea_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spform_005ftextarea_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spform_005ftextarea_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fspform_005ftextarea_0026_005fpath_005fnobody.reuse(_jspx_th_spform_005ftextarea_005f0);
      _jspx_th_spform_005ftextarea_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spform_005ftextarea_005f0, _jsp_getInstanceManager(), _jspx_th_spform_005ftextarea_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/case03/exam_list.jspf(24,4) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVarStatus("status");
      // /WEB-INF/views/case03/exam_list.jspf(24,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("exam");
      // /WEB-INF/views/case03/exam_list.jspf(24,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/case03/exam_list.jspf(24,4) '${ exams }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${ exams }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("					<tr>\n");
            out.write("						<td>\n");
            out.write("							<a href=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/mvc/case03/exam/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ status.index }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ status.index }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a>\n");
            out.write("						</td>\n");
            out.write("						<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ exam.studentId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("						<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ exam.examId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("						<td>");
            if (_jspx_meth_fmt_005fformatDate_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("</td>\n");
            out.write("						<td>\n");
            out.write("							");
            if (_jspx_meth_c_005fforEach_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\n");
            out.write("    					</td>\n");
            out.write("						<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ exam.examPay?'已繳':'未繳' }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("						<td onclick=\"updateExamNote(");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ status.index }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(',');
            out.write(' ');
            out.write('\'');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ exam.examNote }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("')\" class=\"examlink\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ exam.examNote }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("					</tr>\n");
            out.write("				");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    boolean _jspx_th_fmt_005fformatDate_005f0_reused = false;
    try {
      _jspx_th_fmt_005fformatDate_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatDate_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/case03/exam_list.jspf(31,10) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setPattern("yyyy/MM/dd");
      // /WEB-INF/views/case03/exam_list.jspf(31,10) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ exam.examDate }", java.util.Date.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_fmt_005fformatDate_005f0 = _jspx_th_fmt_005fformatDate_005f0.doStartTag();
      if (_jspx_th_fmt_005fformatDate_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f0);
      _jspx_th_fmt_005fformatDate_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatDate_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatDate_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/case03/exam_list.jspf(34,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("slot");
      // /WEB-INF/views/case03/exam_list.jspf(34,7) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/case03/exam_list.jspf(34,7) '${ exam.examSlot }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${ exam.examSlot }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("    							");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ slot }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\n");
            out.write("    						");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }
}
