/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.46
 * Generated at: 2022-05-31 12:09:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.lab;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class fundstock_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("jar:file:/C:/Users/shion/Desktop/java_Spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/springmvc/WEB-INF/lib/javax.servlet.jsp.jstl-1.2.4.jar!/META-INF/fmt.tld", Long.valueOf(1420527028000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.3.29.RELEASE.jar", Long.valueOf(1644731966281L));
    _jspx_dependants.put("/WEB-INF/lib/javax.servlet.jsp.jstl-1.2.4.jar", Long.valueOf(1644731960697L));
    _jspx_dependants.put("jar:file:/C:/Users/shion/Desktop/java_Spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/springmvc/WEB-INF/lib/javax.servlet.jsp.jstl-1.2.4.jar!/META-INF/fn.tld", Long.valueOf(1420527028000L));
    _jspx_dependants.put("jar:file:/C:/Users/shion/Desktop/java_Spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/springmvc/WEB-INF/lib/spring-webmvc-4.3.29.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1600137476000L));
    _jspx_dependants.put("jar:file:/C:/Users/shion/Desktop/java_Spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/springmvc/WEB-INF/lib/javax.servlet.jsp.jstl-1.2.4.jar!/META-INF/c.tld", Long.valueOf(1420527028000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspform_005fform_0026_005fmodelAttribute_005fmethod_005fclass_005faction;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspform_005finput_0026_005fpath_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspform_005ferrors_0026_005fpath_005fcssClass_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspform_005fselect_0026_005fpath;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspform_005foption_0026_005fvalue;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspform_005foptions_0026_005fitems_005fitemValue_005fitemLabel_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fspform_005fform_0026_005fmodelAttribute_005fmethod_005fclass_005faction = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fspform_005finput_0026_005fpath_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fspform_005ferrors_0026_005fpath_005fcssClass_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fspform_005fselect_0026_005fpath = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fspform_005foption_0026_005fvalue = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fspform_005foptions_0026_005fitems_005fitemValue_005fitemLabel_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fspform_005fform_0026_005fmodelAttribute_005fmethod_005fclass_005faction.release();
    _005fjspx_005ftagPool_005fspform_005finput_0026_005fpath_005fnobody.release();
    _005fjspx_005ftagPool_005fspform_005ferrors_0026_005fpath_005fcssClass_005fnobody.release();
    _005fjspx_005ftagPool_005fspform_005fselect_0026_005fpath.release();
    _005fjspx_005ftagPool_005fspform_005foption_0026_005fvalue.release();
    _005fjspx_005ftagPool_005fspform_005foptions_0026_005fitems_005fitemValue_005fitemLabel_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    java.lang.Throwable exception = org.apache.jasper.runtime.JspRuntimeLibrary.getThrowable(request);
    if (exception != null) {
      response.setStatus(javax.servlet.http.HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
    }
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("	<link rel=\"stylesheet\"\n");
      out.write("		href=\"https://unpkg.com/purecss@2.0.6/build/pure-min.css\">\n");
      out.write("	<meta charset=\"UTF-8\">\n");
      out.write("	<title>Fundstock Form</title>\n");
      out.write("	<style type=\"text/css\">\n");
      out.write("	.error {\n");
      out.write("		color: #FF0000\n");
      out.write("	}\n");
      out.write("	</style>\n");
      out.write("	<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js\"></script>\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/util.js\"></script>\n");
      out.write("	<script type=\"text/javascript\" src=\"https://www.gstatic.com/charts/loader.js\"></script>\n");
      out.write("	<script type=\"text/javascript\">\n");
      out.write("      google.charts.load('current', {'packages':['corechart']});\n");
      out.write("      google.charts.setOnLoadCallback(drawChart);\n");
      out.write("      \n");
      out.write("	  function drawChart() {\n");
      out.write("		  drawChart(1);\n");
      out.write("		  drawStockChart('^TWII');\n");
      out.write("	  }\n");
      out.write("	  \n");
      out.write("	  function drawStockChart(symbol) {\n");
      out.write("		  $.get(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/mvc/lab/price/histquotes/\" + symbol, function(quotes, status) {\n");
      out.write("			  //console.log(\"quotes:\" + quotes);\n");
      out.write("			  console.log(\"status:\" + status);\n");
      out.write("			  drawChartHist(symbol, quotes);\n");
      out.write("		  });\n");
      out.write("	  }\n");
      out.write("	  \n");
      out.write("	  function drawChartHist(symbol, quotes) {\n");
      out.write("		  // 建立 data 欄位\n");
      out.write("		  var data =  new google.visualization.DataTable();\n");
      out.write("		  // 定義欄位\n");
      out.write("		  data.addColumn('string', 'Date');\n");
      out.write("		  data.addColumn('number', 'High');\n");
      out.write("		  data.addColumn('number', 'Open');\n");
      out.write("		  data.addColumn('number', 'Close');\n");
      out.write("		  data.addColumn('number', 'Low');\n");
      out.write("		  data.addColumn('number', 'AdjClose');\n");
      out.write("		  data.addColumn('number', 'Volumn');\n");
      out.write("		  // 加入資料\n");
      out.write("		  $.each(quotes, function (i, item) {\n");
      out.write("              var array = [getMD(quotes[i].date), quotes[i].high, quotes[i].open, quotes[i].close, quotes[i].low, quotes[i].adjClose, quotes[i].volume];\n");
      out.write("              data.addRow(array);\n");
      out.write("          });\n");
      out.write("		  console.log(\"data:\" + data);\n");
      out.write("		  // 設定 chart 參數\n");
      out.write("		  var options = {\n");
      out.write("			title: symbol + ' 日K線圖',\n");
      out.write("            legend: 'none',\n");
      out.write("            vAxes: [\n");
      out.write("            	{},\n");
      out.write("                {minValue: 1, maxValue: 6000000}\n");
      out.write("            ],\n");
      out.write("            series: {\n");
      out.write("            	1: {targetAxisIndex: 0, type: 'line', color: '#e7711b'},\n");
      out.write("            	2: {targetAxisIndex: 1, type: 'bars', color: '#cccccc'}\n");
      out.write("            },\n");
      out.write("            	candlestick: {\n");
      out.write("                	fallingColor: {strokeWidth: 0, fill: '#0f9d58'}, // green\n");
      out.write("                    risingColor: {strokeWidth: 0, fill: '#a52714'}   // red\n");
      out.write("             },\n");
      out.write("             chartArea: {left: 50}\n");
      out.write("         };\n");
      out.write("		  // 產生 chart 物件\n");
      out.write("		  var chart = new google.visualization.CandlestickChart(document.getElementById('stockchart'));\n");
      out.write("		  // 繪圖\n");
      out.write("		  chart.draw(data, options);\n");
      out.write("	  }\n");
      out.write("	  \n");
      out.write("      function drawChart(chartId) {\n");
      out.write("\n");
      out.write("        var data = google.visualization.arrayToDataTable([\n");
      out.write("          ['symbol', 'share'],\n");
      out.write("          ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("        ]);\n");
      out.write("\n");
      out.write("        var options = {\n");
      out.write("          title: 'stock info'\n");
      out.write("        };\n");
      out.write("\n");
      out.write("        var chart = new google.visualization.BarChart(document.getElementById('piechart'));\n");
      out.write("        switch(chartId) {\n");
      out.write("        	case 2:\n");
      out.write("        		chart = new google.visualization.PieChart(document.getElementById('piechart'));\n");
      out.write("        		break;\n");
      out.write("        	case 3:\n");
      out.write("        		chart = new google.visualization.ColumnChart(document.getElementById('piechart'));\n");
      out.write("        		break;\n");
      out.write("        	case 4:\n");
      out.write("        		chart = new google.visualization.LineChart(document.getElementById('piechart'));\n");
      out.write("        		break;	\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        chart.draw(data, options);\n");
      out.write("      }\n");
      out.write("	</script>\n");
      out.write("</head>\n");
      out.write("<body style=\"padding: 15px\">\n");
      out.write("	<table>\n");
      out.write("		<tr>\n");
      out.write("			<!-- Fundstock Form -->\n");
      out.write("			<td valign=\"top\">\n");
      out.write("				");
      //  spform:form
      org.springframework.web.servlet.tags.form.FormTag _jspx_th_spform_005fform_005f0 = (org.springframework.web.servlet.tags.form.FormTag) _005fjspx_005ftagPool_005fspform_005fform_0026_005fmodelAttribute_005fmethod_005fclass_005faction.get(org.springframework.web.servlet.tags.form.FormTag.class);
      boolean _jspx_th_spform_005fform_005f0_reused = false;
      try {
        _jspx_th_spform_005fform_005f0.setPageContext(_jspx_page_context);
        _jspx_th_spform_005fform_005f0.setParent(null);
        // /WEB-INF/views/lab/fundstock.jsp(117,4) null
        _jspx_th_spform_005fform_005f0.setDynamicAttribute(null, "class", "pure-form");
        // /WEB-INF/views/lab/fundstock.jsp(117,4) name = method type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_spform_005fform_005f0.setMethod("post");
        // /WEB-INF/views/lab/fundstock.jsp(117,4) name = modelAttribute type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_spform_005fform_005f0.setModelAttribute("fundstock");
        // /WEB-INF/views/lab/fundstock.jsp(117,4) name = action type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_spform_005fform_005f0.setAction((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }/mvc/lab/fundstock/", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        int[] _jspx_push_body_count_spform_005fform_005f0 = new int[] { 0 };
        try {
          int _jspx_eval_spform_005fform_005f0 = _jspx_th_spform_005fform_005f0.doStartTag();
          if (_jspx_eval_spform_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            do {
              out.write("\n");
              out.write("					<fieldset>\n");
              out.write("						<legend>\n");
              out.write("							Fundstock Form | \n");
              out.write("							<a href=\"");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("/html/fund.html\">Fund Form（Ajax）</a>\n");
              out.write("						</legend>\n");
              out.write("						<input type=\"hidden\" id=\"_method\" name=\"_method\" value=\"");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ _method }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("\">\n");
              out.write("							 \n");
              out.write("						基金序號：\n");
              out.write("						");
              if (_jspx_meth_spform_005finput_005f0(_jspx_th_spform_005fform_005f0, _jspx_page_context, _jspx_push_body_count_spform_005fform_005f0))
                return;
              out.write("\n");
              out.write("						");
              //  spform:errors
              org.springframework.web.servlet.tags.form.ErrorsTag _jspx_th_spform_005ferrors_005f0 = (org.springframework.web.servlet.tags.form.ErrorsTag) _005fjspx_005ftagPool_005fspform_005ferrors_0026_005fpath_005fcssClass_005fnobody.get(org.springframework.web.servlet.tags.form.ErrorsTag.class);
              boolean _jspx_th_spform_005ferrors_005f0_reused = false;
              try {
                _jspx_th_spform_005ferrors_005f0.setPageContext(_jspx_page_context);
                _jspx_th_spform_005ferrors_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spform_005fform_005f0);
                // /WEB-INF/views/lab/fundstock.jsp(129,6) name = path type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_spform_005ferrors_005f0.setPath("fid");
                // /WEB-INF/views/lab/fundstock.jsp(129,6) name = cssClass type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_spform_005ferrors_005f0.setCssClass("error");
                int[] _jspx_push_body_count_spform_005ferrors_005f0 = new int[] { 0 };
                try {
                  int _jspx_eval_spform_005ferrors_005f0 = _jspx_th_spform_005ferrors_005f0.doStartTag();
                  if (_jspx_th_spform_005ferrors_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                    return;
                  }
                } catch (java.lang.Throwable _jspx_exception) {
                  while (_jspx_push_body_count_spform_005ferrors_005f0[0]-- > 0)
                    out = _jspx_page_context.popBody();
                  _jspx_th_spform_005ferrors_005f0.doCatch(_jspx_exception);
                } finally {
                  _jspx_th_spform_005ferrors_005f0.doFinally();
                }
                _005fjspx_005ftagPool_005fspform_005ferrors_0026_005fpath_005fcssClass_005fnobody.reuse(_jspx_th_spform_005ferrors_005f0);
                _jspx_th_spform_005ferrors_005f0_reused = true;
              } finally {
                org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spform_005ferrors_005f0, _jsp_getInstanceManager(), _jspx_th_spform_005ferrors_005f0_reused);
              }
              out.write("\n");
              out.write("						<p />\n");
              out.write("						股票代號：\n");
              out.write("						");
              if (_jspx_meth_spform_005finput_005f1(_jspx_th_spform_005fform_005f0, _jspx_page_context, _jspx_push_body_count_spform_005fform_005f0))
                return;
              out.write("\n");
              out.write("						");
              //  spform:errors
              org.springframework.web.servlet.tags.form.ErrorsTag _jspx_th_spform_005ferrors_005f1 = (org.springframework.web.servlet.tags.form.ErrorsTag) _005fjspx_005ftagPool_005fspform_005ferrors_0026_005fpath_005fcssClass_005fnobody.get(org.springframework.web.servlet.tags.form.ErrorsTag.class);
              boolean _jspx_th_spform_005ferrors_005f1_reused = false;
              try {
                _jspx_th_spform_005ferrors_005f1.setPageContext(_jspx_page_context);
                _jspx_th_spform_005ferrors_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spform_005fform_005f0);
                // /WEB-INF/views/lab/fundstock.jsp(133,6) name = path type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_spform_005ferrors_005f1.setPath("symbol");
                // /WEB-INF/views/lab/fundstock.jsp(133,6) name = cssClass type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_spform_005ferrors_005f1.setCssClass("error");
                int[] _jspx_push_body_count_spform_005ferrors_005f1 = new int[] { 0 };
                try {
                  int _jspx_eval_spform_005ferrors_005f1 = _jspx_th_spform_005ferrors_005f1.doStartTag();
                  if (_jspx_th_spform_005ferrors_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                    return;
                  }
                } catch (java.lang.Throwable _jspx_exception) {
                  while (_jspx_push_body_count_spform_005ferrors_005f1[0]-- > 0)
                    out = _jspx_page_context.popBody();
                  _jspx_th_spform_005ferrors_005f1.doCatch(_jspx_exception);
                } finally {
                  _jspx_th_spform_005ferrors_005f1.doFinally();
                }
                _005fjspx_005ftagPool_005fspform_005ferrors_0026_005fpath_005fcssClass_005fnobody.reuse(_jspx_th_spform_005ferrors_005f1);
                _jspx_th_spform_005ferrors_005f1_reused = true;
              } finally {
                org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spform_005ferrors_005f1, _jsp_getInstanceManager(), _jspx_th_spform_005ferrors_005f1_reused);
              }
              out.write("\n");
              out.write("						<p />\n");
              out.write("						股票數量：\n");
              out.write("						");
              if (_jspx_meth_spform_005finput_005f2(_jspx_th_spform_005fform_005f0, _jspx_page_context, _jspx_push_body_count_spform_005fform_005f0))
                return;
              out.write("\n");
              out.write("						");
              //  spform:errors
              org.springframework.web.servlet.tags.form.ErrorsTag _jspx_th_spform_005ferrors_005f2 = (org.springframework.web.servlet.tags.form.ErrorsTag) _005fjspx_005ftagPool_005fspform_005ferrors_0026_005fpath_005fcssClass_005fnobody.get(org.springframework.web.servlet.tags.form.ErrorsTag.class);
              boolean _jspx_th_spform_005ferrors_005f2_reused = false;
              try {
                _jspx_th_spform_005ferrors_005f2.setPageContext(_jspx_page_context);
                _jspx_th_spform_005ferrors_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spform_005fform_005f0);
                // /WEB-INF/views/lab/fundstock.jsp(137,6) name = path type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_spform_005ferrors_005f2.setPath("share");
                // /WEB-INF/views/lab/fundstock.jsp(137,6) name = cssClass type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_spform_005ferrors_005f2.setCssClass("error");
                int[] _jspx_push_body_count_spform_005ferrors_005f2 = new int[] { 0 };
                try {
                  int _jspx_eval_spform_005ferrors_005f2 = _jspx_th_spform_005ferrors_005f2.doStartTag();
                  if (_jspx_th_spform_005ferrors_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                    return;
                  }
                } catch (java.lang.Throwable _jspx_exception) {
                  while (_jspx_push_body_count_spform_005ferrors_005f2[0]-- > 0)
                    out = _jspx_page_context.popBody();
                  _jspx_th_spform_005ferrors_005f2.doCatch(_jspx_exception);
                } finally {
                  _jspx_th_spform_005ferrors_005f2.doFinally();
                }
                _005fjspx_005ftagPool_005fspform_005ferrors_0026_005fpath_005fcssClass_005fnobody.reuse(_jspx_th_spform_005ferrors_005f2);
                _jspx_th_spform_005ferrors_005f2_reused = true;
              } finally {
                org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spform_005ferrors_005f2, _jsp_getInstanceManager(), _jspx_th_spform_005ferrors_005f2_reused);
              }
              out.write("\n");
              out.write("						<p />\n");
              out.write("						基金名稱：\n");
              out.write("						");
              //  spform:select
              org.springframework.web.servlet.tags.form.SelectTag _jspx_th_spform_005fselect_005f0 = (org.springframework.web.servlet.tags.form.SelectTag) _005fjspx_005ftagPool_005fspform_005fselect_0026_005fpath.get(org.springframework.web.servlet.tags.form.SelectTag.class);
              boolean _jspx_th_spform_005fselect_005f0_reused = false;
              try {
                _jspx_th_spform_005fselect_005f0.setPageContext(_jspx_page_context);
                _jspx_th_spform_005fselect_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spform_005fform_005f0);
                // /WEB-INF/views/lab/fundstock.jsp(140,6) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_spform_005fselect_005f0.setPath("fid");
                int[] _jspx_push_body_count_spform_005fselect_005f0 = new int[] { 0 };
                try {
                  int _jspx_eval_spform_005fselect_005f0 = _jspx_th_spform_005fselect_005f0.doStartTag();
                  if (_jspx_eval_spform_005fselect_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                    do {
                      out.write("\n");
                      out.write("							");
                      //  spform:option
                      org.springframework.web.servlet.tags.form.OptionTag _jspx_th_spform_005foption_005f0 = (org.springframework.web.servlet.tags.form.OptionTag) _005fjspx_005ftagPool_005fspform_005foption_0026_005fvalue.get(org.springframework.web.servlet.tags.form.OptionTag.class);
                      boolean _jspx_th_spform_005foption_005f0_reused = false;
                      try {
                        _jspx_th_spform_005foption_005f0.setPageContext(_jspx_page_context);
                        _jspx_th_spform_005foption_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spform_005fselect_005f0);
                        // /WEB-INF/views/lab/fundstock.jsp(141,7) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                        _jspx_th_spform_005foption_005f0.setValue("");
                        int[] _jspx_push_body_count_spform_005foption_005f0 = new int[] { 0 };
                        try {
                          int _jspx_eval_spform_005foption_005f0 = _jspx_th_spform_005foption_005f0.doStartTag();
                          if (_jspx_eval_spform_005foption_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                            java.lang.Object value = null;
                            java.lang.String displayValue = null;
                            if (_jspx_eval_spform_005foption_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                              _jspx_push_body_count_spform_005foption_005f0[0]++;
                              out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_spform_005foption_005f0);
                            }
                            value = (java.lang.Object) _jspx_page_context.findAttribute("value");
                            displayValue = (java.lang.String) _jspx_page_context.findAttribute("displayValue");
                            do {
                              out.write('請');
                              out.write('選');
                              out.write('擇');
                              int evalDoAfterBody = _jspx_th_spform_005foption_005f0.doAfterBody();
                              value = (java.lang.Object) _jspx_page_context.findAttribute("value");
                              displayValue = (java.lang.String) _jspx_page_context.findAttribute("displayValue");
                              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                              break;
                            } while (true);
                            if (_jspx_eval_spform_005foption_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                              out = _jspx_page_context.popBody();
                              _jspx_push_body_count_spform_005foption_005f0[0]--;
                            }
                          }
                          if (_jspx_th_spform_005foption_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                            return;
                          }
                        } catch (java.lang.Throwable _jspx_exception) {
                          while (_jspx_push_body_count_spform_005foption_005f0[0]-- > 0)
                            out = _jspx_page_context.popBody();
                          _jspx_th_spform_005foption_005f0.doCatch(_jspx_exception);
                        } finally {
                          _jspx_th_spform_005foption_005f0.doFinally();
                        }
                        _005fjspx_005ftagPool_005fspform_005foption_0026_005fvalue.reuse(_jspx_th_spform_005foption_005f0);
                        _jspx_th_spform_005foption_005f0_reused = true;
                      } finally {
                        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spform_005foption_005f0, _jsp_getInstanceManager(), _jspx_th_spform_005foption_005f0_reused);
                      }
                      out.write("\n");
                      out.write("							");
                      if (_jspx_meth_spform_005foptions_005f0(_jspx_th_spform_005fselect_005f0, _jspx_page_context, _jspx_push_body_count_spform_005fselect_005f0))
                        return;
                      out.write("\n");
                      out.write("						");
                      int evalDoAfterBody = _jspx_th_spform_005fselect_005f0.doAfterBody();
                      if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                        break;
                    } while (true);
                  }
                  if (_jspx_th_spform_005fselect_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                    return;
                  }
                } catch (java.lang.Throwable _jspx_exception) {
                  while (_jspx_push_body_count_spform_005fselect_005f0[0]-- > 0)
                    out = _jspx_page_context.popBody();
                  _jspx_th_spform_005fselect_005f0.doCatch(_jspx_exception);
                } finally {
                  _jspx_th_spform_005fselect_005f0.doFinally();
                }
                _005fjspx_005ftagPool_005fspform_005fselect_0026_005fpath.reuse(_jspx_th_spform_005fselect_005f0);
                _jspx_th_spform_005fselect_005f0_reused = true;
              } finally {
                org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spform_005fselect_005f0, _jsp_getInstanceManager(), _jspx_th_spform_005fselect_005f0_reused);
              }
              out.write("\n");
              out.write("						<p />\n");
              out.write("						<button type=\"submit\" class=\"pure-button pure-button-primary\"\n");
              out.write("							");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ _method=='POST'}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write(">新增</button>\n");
              out.write("						<button type=\"submit\" class=\"pure-button pure-button-primary\"\n");
              out.write("							");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ _method=='PUT'}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write(">修改</button>\n");
              out.write("						<p />\n");
              out.write("						");
              //  spform:errors
              org.springframework.web.servlet.tags.form.ErrorsTag _jspx_th_spform_005ferrors_005f3 = (org.springframework.web.servlet.tags.form.ErrorsTag) _005fjspx_005ftagPool_005fspform_005ferrors_0026_005fpath_005fcssClass_005fnobody.get(org.springframework.web.servlet.tags.form.ErrorsTag.class);
              boolean _jspx_th_spform_005ferrors_005f3_reused = false;
              try {
                _jspx_th_spform_005ferrors_005f3.setPageContext(_jspx_page_context);
                _jspx_th_spform_005ferrors_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spform_005fform_005f0);
                // /WEB-INF/views/lab/fundstock.jsp(150,6) name = path type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_spform_005ferrors_005f3.setPath("*");
                // /WEB-INF/views/lab/fundstock.jsp(150,6) name = cssClass type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_spform_005ferrors_005f3.setCssClass("error");
                int[] _jspx_push_body_count_spform_005ferrors_005f3 = new int[] { 0 };
                try {
                  int _jspx_eval_spform_005ferrors_005f3 = _jspx_th_spform_005ferrors_005f3.doStartTag();
                  if (_jspx_th_spform_005ferrors_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                    return;
                  }
                } catch (java.lang.Throwable _jspx_exception) {
                  while (_jspx_push_body_count_spform_005ferrors_005f3[0]-- > 0)
                    out = _jspx_page_context.popBody();
                  _jspx_th_spform_005ferrors_005f3.doCatch(_jspx_exception);
                } finally {
                  _jspx_th_spform_005ferrors_005f3.doFinally();
                }
                _005fjspx_005ftagPool_005fspform_005ferrors_0026_005fpath_005fcssClass_005fnobody.reuse(_jspx_th_spform_005ferrors_005f3);
                _jspx_th_spform_005ferrors_005f3_reused = true;
              } finally {
                org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spform_005ferrors_005f3, _jsp_getInstanceManager(), _jspx_th_spform_005ferrors_005f3_reused);
              }
              out.write("\n");
              out.write("					</fieldset>					\n");
              out.write("				");
              int evalDoAfterBody = _jspx_th_spform_005fform_005f0.doAfterBody();
              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
          }
          if (_jspx_th_spform_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            return;
          }
        } catch (java.lang.Throwable _jspx_exception) {
          while (_jspx_push_body_count_spform_005fform_005f0[0]-- > 0)
            out = _jspx_page_context.popBody();
          _jspx_th_spform_005fform_005f0.doCatch(_jspx_exception);
        } finally {
          _jspx_th_spform_005fform_005f0.doFinally();
        }
        _005fjspx_005ftagPool_005fspform_005fform_0026_005fmodelAttribute_005fmethod_005fclass_005faction.reuse(_jspx_th_spform_005fform_005f0);
        _jspx_th_spform_005fform_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spform_005fform_005f0, _jsp_getInstanceManager(), _jspx_th_spform_005fform_005f0_reused);
      }
      out.write("\n");
      out.write("				\n");
      out.write("			\n");
      out.write("			<!-- Fundstock List -->\n");
      out.write("			<td valign=\"top\">\n");
      out.write("				<form class=\"pure-form\">\n");
      out.write("					<fieldset>\n");
      out.write("						<legend>\n");
      out.write("							Fundstock List&nbsp;|&nbsp;\n");
      out.write("							<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/mvc/lab/fundstock/page/0\">全部</a>\n");
      out.write("							&nbsp;|&nbsp;\n");
      out.write("							");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("						</legend>\n");
      out.write("						<table class=\"pure-table pure-table-bordered\">\n");
      out.write("							<thead>\n");
      out.write("								<tr>\n");
      out.write("									<th>股票序號</th>\n");
      out.write("									<th>股票代號</th>\n");
      out.write("									<th>股票數量</th>\n");
      out.write("									<th>基金序號</th>\n");
      out.write("									<th>基金名稱</th>\n");
      out.write("								</tr>\n");
      out.write("							</thead>\n");
      out.write("							<tbody>\n");
      out.write("								");
      if (_jspx_meth_c_005fforEach_005f2(_jspx_page_context))
        return;
      out.write("\n");
      out.write("							</tbody>\n");
      out.write("						</table>\n");
      out.write("					</fieldset>\n");
      out.write("				</form>\n");
      out.write("			</td>\n");
      out.write("			<!-- Fundstock chart -->\n");
      out.write("			<td valign=\"top\">\n");
      out.write("				<form class=\"pure-form\">\n");
      out.write("					<fieldset>\n");
      out.write("						<legend>\n");
      out.write("							Fundstock Chart |\n");
      out.write("							<a href=\"#\" onclick=\"drawChart(1)\">bar</a> |\n");
      out.write("							<a href=\"#\" onclick=\"drawChart(2)\">pie</a> |\n");
      out.write("							<a href=\"#\" onclick=\"drawChart(3)\">column</a> |\n");
      out.write("							<a href=\"#\" onclick=\"drawChart(4)\">line</a>\n");
      out.write("						</legend>\n");
      out.write("						<div id=\"piechart\" style=\"width: 500px; height: 300px;\"></div>\n");
      out.write("					</fieldset>\n");
      out.write("				</form>\n");
      out.write("			</td>\n");
      out.write("		</tr>\n");
      out.write("		<tr>\n");
      out.write("			<td colspan=\"3\" valign=\"top\">\n");
      out.write("				<form class=\"pure-form\">\n");
      out.write("					<fieldset>\n");
      out.write("						<legend>\n");
      out.write("							Fundstock Chart | <a href=\"#\" onclick=\"drawStockChart('^TWII')\">加權股價</a>\n");
      out.write("						</legend>\n");
      out.write("						<div id=\"stockchart\" style=\"width: 1500px; height: 500px;\"></div>\n");
      out.write("					</fieldset>\n");
      out.write("				</form>\n");
      out.write("			</td>\n");
      out.write("		</tr>\n");
      out.write("	</table>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/lab/fundstock.jsp(86,10) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("map");
      // /WEB-INF/views/lab/fundstock.jsp(86,10) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/lab/fundstock.jsp(86,10) '${ groupMap }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${ groupMap }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("			['");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ map.key }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('\'');
            out.write(',');
            out.write(' ');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ map.value }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("],\n");
            out.write("		  ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spform_005finput_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_spform_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_spform_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spform:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_spform_005finput_005f0 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fspform_005finput_0026_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    boolean _jspx_th_spform_005finput_005f0_reused = false;
    try {
      _jspx_th_spform_005finput_005f0.setPageContext(_jspx_page_context);
      _jspx_th_spform_005finput_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spform_005fform_005f0);
      // /WEB-INF/views/lab/fundstock.jsp(128,6) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spform_005finput_005f0.setPath("fid");
      int[] _jspx_push_body_count_spform_005finput_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_spform_005finput_005f0 = _jspx_th_spform_005finput_005f0.doStartTag();
        if (_jspx_th_spform_005finput_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spform_005finput_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spform_005finput_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spform_005finput_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fspform_005finput_0026_005fpath_005fnobody.reuse(_jspx_th_spform_005finput_005f0);
      _jspx_th_spform_005finput_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spform_005finput_005f0, _jsp_getInstanceManager(), _jspx_th_spform_005finput_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spform_005finput_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_spform_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_spform_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spform:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_spform_005finput_005f1 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fspform_005finput_0026_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    boolean _jspx_th_spform_005finput_005f1_reused = false;
    try {
      _jspx_th_spform_005finput_005f1.setPageContext(_jspx_page_context);
      _jspx_th_spform_005finput_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spform_005fform_005f0);
      // /WEB-INF/views/lab/fundstock.jsp(132,6) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spform_005finput_005f1.setPath("symbol");
      int[] _jspx_push_body_count_spform_005finput_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_spform_005finput_005f1 = _jspx_th_spform_005finput_005f1.doStartTag();
        if (_jspx_th_spform_005finput_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spform_005finput_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spform_005finput_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spform_005finput_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fspform_005finput_0026_005fpath_005fnobody.reuse(_jspx_th_spform_005finput_005f1);
      _jspx_th_spform_005finput_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spform_005finput_005f1, _jsp_getInstanceManager(), _jspx_th_spform_005finput_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spform_005finput_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_spform_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_spform_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spform:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_spform_005finput_005f2 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fspform_005finput_0026_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    boolean _jspx_th_spform_005finput_005f2_reused = false;
    try {
      _jspx_th_spform_005finput_005f2.setPageContext(_jspx_page_context);
      _jspx_th_spform_005finput_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spform_005fform_005f0);
      // /WEB-INF/views/lab/fundstock.jsp(136,6) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spform_005finput_005f2.setPath("share");
      int[] _jspx_push_body_count_spform_005finput_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_spform_005finput_005f2 = _jspx_th_spform_005finput_005f2.doStartTag();
        if (_jspx_th_spform_005finput_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spform_005finput_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spform_005finput_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spform_005finput_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fspform_005finput_0026_005fpath_005fnobody.reuse(_jspx_th_spform_005finput_005f2);
      _jspx_th_spform_005finput_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spform_005finput_005f2, _jsp_getInstanceManager(), _jspx_th_spform_005finput_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spform_005foptions_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_spform_005fselect_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_spform_005fselect_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spform:options
    org.springframework.web.servlet.tags.form.OptionsTag _jspx_th_spform_005foptions_005f0 = (org.springframework.web.servlet.tags.form.OptionsTag) _005fjspx_005ftagPool_005fspform_005foptions_0026_005fitems_005fitemValue_005fitemLabel_005fnobody.get(org.springframework.web.servlet.tags.form.OptionsTag.class);
    boolean _jspx_th_spform_005foptions_005f0_reused = false;
    try {
      _jspx_th_spform_005foptions_005f0.setPageContext(_jspx_page_context);
      _jspx_th_spform_005foptions_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spform_005fselect_005f0);
      // /WEB-INF/views/lab/fundstock.jsp(142,7) name = items type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spform_005foptions_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ funds }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/views/lab/fundstock.jsp(142,7) name = itemValue type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spform_005foptions_005f0.setItemValue("fid");
      // /WEB-INF/views/lab/fundstock.jsp(142,7) name = itemLabel type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spform_005foptions_005f0.setItemLabel("fname");
      int[] _jspx_push_body_count_spform_005foptions_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_spform_005foptions_005f0 = _jspx_th_spform_005foptions_005f0.doStartTag();
        if (_jspx_th_spform_005foptions_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spform_005foptions_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spform_005foptions_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spform_005foptions_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fspform_005foptions_0026_005fitems_005fitemValue_005fitemLabel_005fnobody.reuse(_jspx_th_spform_005foptions_005f0);
      _jspx_th_spform_005foptions_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spform_005foptions_005f0, _jsp_getInstanceManager(), _jspx_th_spform_005foptions_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /WEB-INF/views/lab/fundstock.jsp(163,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("num");
      // /WEB-INF/views/lab/fundstock.jsp(163,7) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setBegin(1);
      // /WEB-INF/views/lab/fundstock.jsp(163,7) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setEnd(((java.lang.Integer) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageTotalCount+1 }", int.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).intValue());
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("								<a href=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/mvc/lab/fundstock/page/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ num }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ num }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a>\n");
            out.write("							");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f2_reused = false;
    try {
      _jspx_th_c_005fforEach_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f2.setParent(null);
      // /WEB-INF/views/lab/fundstock.jsp(178,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setVar("fundstock");
      // /WEB-INF/views/lab/fundstock.jsp(178,8) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/lab/fundstock.jsp(178,8) '${ fundstocks }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${ fundstocks }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f2 = _jspx_th_c_005fforEach_005f2.doStartTag();
        if (_jspx_eval_c_005fforEach_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("									<tr>\n");
            out.write("										<td><a\n");
            out.write("											href=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/mvc/lab/fundstock/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ fundstock.sid }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ fundstock.sid }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a></td>\n");
            out.write("										<td>\n");
            out.write("											<a href=\"#\" onclick=\"drawStockChart('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ fundstock.symbol }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("')\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ fundstock.symbol }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a>\n");
            out.write("										</td>\n");
            out.write("										<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ fundstock.share }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("										<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ fundstock.fund.fid }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("										<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ fundstock.fund.fname }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("									</tr>\n");
            out.write("								");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f2.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f2);
      _jspx_th_c_005fforEach_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f2_reused);
    }
    return false;
  }
}
