/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.46
 * Generated at: 2022-05-31 12:09:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.case04;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class stock_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("jar:file:/C:/Users/shion/Desktop/java_Spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/springmvc/WEB-INF/lib/javax.servlet.jsp.jstl-1.2.4.jar!/META-INF/fmt.tld", Long.valueOf(1420527028000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.3.29.RELEASE.jar", Long.valueOf(1644731966281L));
    _jspx_dependants.put("/WEB-INF/lib/javax.servlet.jsp.jstl-1.2.4.jar", Long.valueOf(1644731960697L));
    _jspx_dependants.put("jar:file:/C:/Users/shion/Desktop/java_Spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/springmvc/WEB-INF/lib/javax.servlet.jsp.jstl-1.2.4.jar!/META-INF/fn.tld", Long.valueOf(1420527028000L));
    _jspx_dependants.put("jar:file:/C:/Users/shion/Desktop/java_Spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/springmvc/WEB-INF/lib/spring-webmvc-4.3.29.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1600137476000L));
    _jspx_dependants.put("jar:file:/C:/Users/shion/Desktop/java_Spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/springmvc/WEB-INF/lib/javax.servlet.jsp.jstl-1.2.4.jar!/META-INF/c.tld", Long.valueOf(1420527028000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspform_005fform_0026_005fmodelAttribute_005fmethod_005fclass_005faction;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspform_005finput_0026_005fpath_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspform_005ferrors_0026_005fpath_005fcssClass_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fspform_005fform_0026_005fmodelAttribute_005fmethod_005fclass_005faction = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fspform_005finput_0026_005fpath_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fspform_005ferrors_0026_005fpath_005fcssClass_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fspform_005fform_0026_005fmodelAttribute_005fmethod_005fclass_005faction.release();
    _005fjspx_005ftagPool_005fspform_005finput_0026_005fpath_005fnobody.release();
    _005fjspx_005ftagPool_005fspform_005ferrors_0026_005fpath_005fcssClass_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    java.lang.Throwable exception = org.apache.jasper.runtime.JspRuntimeLibrary.getThrowable(request);
    if (exception != null) {
      response.setStatus(javax.servlet.http.HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
    }
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write(" \n");
      out.write("   \n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<link rel=\"stylesheet\" href=\"https://unpkg.com/purecss@2.0.6/build/pure-min.css\">\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Stock Form</title>\n");
      out.write("<style type=\"text/css\">\n");
      out.write("	.error {\n");
      out.write("		color: #FF0000\n");
      out.write("	}\n");
      out.write("	.info {\n");
      out.write("		color: #005100\n");
      out.write("	}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body style=\"padding: 15px\">\n");
      out.write("	\n");
      out.write("	");
      //  spform:form
      org.springframework.web.servlet.tags.form.FormTag _jspx_th_spform_005fform_005f0 = (org.springframework.web.servlet.tags.form.FormTag) _005fjspx_005ftagPool_005fspform_005fform_0026_005fmodelAttribute_005fmethod_005fclass_005faction.get(org.springframework.web.servlet.tags.form.FormTag.class);
      boolean _jspx_th_spform_005fform_005f0_reused = false;
      try {
        _jspx_th_spform_005fform_005f0.setPageContext(_jspx_page_context);
        _jspx_th_spform_005fform_005f0.setParent(null);
        // /WEB-INF/views/case04/stock.jsp(26,1) null
        _jspx_th_spform_005fform_005f0.setDynamicAttribute(null, "class", "pure-form");
        // /WEB-INF/views/case04/stock.jsp(26,1) name = method type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_spform_005fform_005f0.setMethod("post");
        // /WEB-INF/views/case04/stock.jsp(26,1) name = modelAttribute type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_spform_005fform_005f0.setModelAttribute("stock");
        // /WEB-INF/views/case04/stock.jsp(26,1) name = action type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_spform_005fform_005f0.setAction((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }/mvc/case04/stock/", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        int[] _jspx_push_body_count_spform_005fform_005f0 = new int[] { 0 };
        try {
          int _jspx_eval_spform_005fform_005f0 = _jspx_th_spform_005fform_005f0.doStartTag();
          if (_jspx_eval_spform_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            do {
              out.write("\n");
              out.write("		<fieldset>\n");
              out.write("			<legend>Stock Form</legend>\n");
              out.write("			代號：");
              if (_jspx_meth_spform_005finput_005f0(_jspx_th_spform_005fform_005f0, _jspx_page_context, _jspx_push_body_count_spform_005fform_005f0))
                return;
              out.write("\n");
              out.write("	    		 ");
              //  spform:errors
              org.springframework.web.servlet.tags.form.ErrorsTag _jspx_th_spform_005ferrors_005f0 = (org.springframework.web.servlet.tags.form.ErrorsTag) _005fjspx_005ftagPool_005fspform_005ferrors_0026_005fpath_005fcssClass_005fnobody.get(org.springframework.web.servlet.tags.form.ErrorsTag.class);
              boolean _jspx_th_spform_005ferrors_005f0_reused = false;
              try {
                _jspx_th_spform_005ferrors_005f0.setPageContext(_jspx_page_context);
                _jspx_th_spform_005ferrors_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spform_005fform_005f0);
                // /WEB-INF/views/case04/stock.jsp(33,8) name = path type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_spform_005ferrors_005f0.setPath("symbol");
                // /WEB-INF/views/case04/stock.jsp(33,8) name = cssClass type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_spform_005ferrors_005f0.setCssClass("error");
                int[] _jspx_push_body_count_spform_005ferrors_005f0 = new int[] { 0 };
                try {
                  int _jspx_eval_spform_005ferrors_005f0 = _jspx_th_spform_005ferrors_005f0.doStartTag();
                  if (_jspx_th_spform_005ferrors_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                    return;
                  }
                } catch (java.lang.Throwable _jspx_exception) {
                  while (_jspx_push_body_count_spform_005ferrors_005f0[0]-- > 0)
                    out = _jspx_page_context.popBody();
                  _jspx_th_spform_005ferrors_005f0.doCatch(_jspx_exception);
                } finally {
                  _jspx_th_spform_005ferrors_005f0.doFinally();
                }
                _005fjspx_005ftagPool_005fspform_005ferrors_0026_005fpath_005fcssClass_005fnobody.reuse(_jspx_th_spform_005ferrors_005f0);
                _jspx_th_spform_005ferrors_005f0_reused = true;
              } finally {
                org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spform_005ferrors_005f0, _jsp_getInstanceManager(), _jspx_th_spform_005ferrors_005f0_reused);
              }
              out.write("<p />\n");
              out.write("	    	價格：");
              if (_jspx_meth_spform_005finput_005f1(_jspx_th_spform_005fform_005f0, _jspx_page_context, _jspx_push_body_count_spform_005fform_005f0))
                return;
              out.write("\n");
              out.write("	    		 ");
              //  spform:errors
              org.springframework.web.servlet.tags.form.ErrorsTag _jspx_th_spform_005ferrors_005f1 = (org.springframework.web.servlet.tags.form.ErrorsTag) _005fjspx_005ftagPool_005fspform_005ferrors_0026_005fpath_005fcssClass_005fnobody.get(org.springframework.web.servlet.tags.form.ErrorsTag.class);
              boolean _jspx_th_spform_005ferrors_005f1_reused = false;
              try {
                _jspx_th_spform_005ferrors_005f1.setPageContext(_jspx_page_context);
                _jspx_th_spform_005ferrors_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spform_005fform_005f0);
                // /WEB-INF/views/case04/stock.jsp(35,8) name = path type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_spform_005ferrors_005f1.setPath("price");
                // /WEB-INF/views/case04/stock.jsp(35,8) name = cssClass type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_spform_005ferrors_005f1.setCssClass("error");
                int[] _jspx_push_body_count_spform_005ferrors_005f1 = new int[] { 0 };
                try {
                  int _jspx_eval_spform_005ferrors_005f1 = _jspx_th_spform_005ferrors_005f1.doStartTag();
                  if (_jspx_th_spform_005ferrors_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                    return;
                  }
                } catch (java.lang.Throwable _jspx_exception) {
                  while (_jspx_push_body_count_spform_005ferrors_005f1[0]-- > 0)
                    out = _jspx_page_context.popBody();
                  _jspx_th_spform_005ferrors_005f1.doCatch(_jspx_exception);
                } finally {
                  _jspx_th_spform_005ferrors_005f1.doFinally();
                }
                _005fjspx_005ftagPool_005fspform_005ferrors_0026_005fpath_005fcssClass_005fnobody.reuse(_jspx_th_spform_005ferrors_005f1);
                _jspx_th_spform_005ferrors_005f1_reused = true;
              } finally {
                org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spform_005ferrors_005f1, _jsp_getInstanceManager(), _jspx_th_spform_005ferrors_005f1_reused);
              }
              out.write("<p />\n");
              out.write("	    	數量：");
              if (_jspx_meth_spform_005finput_005f2(_jspx_th_spform_005fform_005f0, _jspx_page_context, _jspx_push_body_count_spform_005fform_005f0))
                return;
              out.write("\n");
              out.write("	    		 ");
              //  spform:errors
              org.springframework.web.servlet.tags.form.ErrorsTag _jspx_th_spform_005ferrors_005f2 = (org.springframework.web.servlet.tags.form.ErrorsTag) _005fjspx_005ftagPool_005fspform_005ferrors_0026_005fpath_005fcssClass_005fnobody.get(org.springframework.web.servlet.tags.form.ErrorsTag.class);
              boolean _jspx_th_spform_005ferrors_005f2_reused = false;
              try {
                _jspx_th_spform_005ferrors_005f2.setPageContext(_jspx_page_context);
                _jspx_th_spform_005ferrors_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spform_005fform_005f0);
                // /WEB-INF/views/case04/stock.jsp(37,8) name = path type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_spform_005ferrors_005f2.setPath("amount");
                // /WEB-INF/views/case04/stock.jsp(37,8) name = cssClass type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_spform_005ferrors_005f2.setCssClass("error");
                int[] _jspx_push_body_count_spform_005ferrors_005f2 = new int[] { 0 };
                try {
                  int _jspx_eval_spform_005ferrors_005f2 = _jspx_th_spform_005ferrors_005f2.doStartTag();
                  if (_jspx_th_spform_005ferrors_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                    return;
                  }
                } catch (java.lang.Throwable _jspx_exception) {
                  while (_jspx_push_body_count_spform_005ferrors_005f2[0]-- > 0)
                    out = _jspx_page_context.popBody();
                  _jspx_th_spform_005ferrors_005f2.doCatch(_jspx_exception);
                } finally {
                  _jspx_th_spform_005ferrors_005f2.doFinally();
                }
                _005fjspx_005ftagPool_005fspform_005ferrors_0026_005fpath_005fcssClass_005fnobody.reuse(_jspx_th_spform_005ferrors_005f2);
                _jspx_th_spform_005ferrors_005f2_reused = true;
              } finally {
                org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spform_005ferrors_005f2, _jsp_getInstanceManager(), _jspx_th_spform_005ferrors_005f2_reused);
              }
              out.write("<p />\n");
              out.write("	        <button type=\"submit\" class=\"pure-button pure-button-primary\">新增</button>\n");
              out.write("	        <p />\n");
              out.write("	        ");
              //  spform:errors
              org.springframework.web.servlet.tags.form.ErrorsTag _jspx_th_spform_005ferrors_005f3 = (org.springframework.web.servlet.tags.form.ErrorsTag) _005fjspx_005ftagPool_005fspform_005ferrors_0026_005fpath_005fcssClass_005fnobody.get(org.springframework.web.servlet.tags.form.ErrorsTag.class);
              boolean _jspx_th_spform_005ferrors_005f3_reused = false;
              try {
                _jspx_th_spform_005ferrors_005f3.setPageContext(_jspx_page_context);
                _jspx_th_spform_005ferrors_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spform_005fform_005f0);
                // /WEB-INF/views/case04/stock.jsp(40,9) name = path type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_spform_005ferrors_005f3.setPath("*");
                // /WEB-INF/views/case04/stock.jsp(40,9) name = cssClass type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_spform_005ferrors_005f3.setCssClass("info");
                int[] _jspx_push_body_count_spform_005ferrors_005f3 = new int[] { 0 };
                try {
                  int _jspx_eval_spform_005ferrors_005f3 = _jspx_th_spform_005ferrors_005f3.doStartTag();
                  if (_jspx_th_spform_005ferrors_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                    return;
                  }
                } catch (java.lang.Throwable _jspx_exception) {
                  while (_jspx_push_body_count_spform_005ferrors_005f3[0]-- > 0)
                    out = _jspx_page_context.popBody();
                  _jspx_th_spform_005ferrors_005f3.doCatch(_jspx_exception);
                } finally {
                  _jspx_th_spform_005ferrors_005f3.doFinally();
                }
                _005fjspx_005ftagPool_005fspform_005ferrors_0026_005fpath_005fcssClass_005fnobody.reuse(_jspx_th_spform_005ferrors_005f3);
                _jspx_th_spform_005ferrors_005f3_reused = true;
              } finally {
                org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spform_005ferrors_005f3, _jsp_getInstanceManager(), _jspx_th_spform_005ferrors_005f3_reused);
              }
              out.write("\n");
              out.write("	    </fieldset>\n");
              out.write("    ");
              int evalDoAfterBody = _jspx_th_spform_005fform_005f0.doAfterBody();
              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
          }
          if (_jspx_th_spform_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            return;
          }
        } catch (java.lang.Throwable _jspx_exception) {
          while (_jspx_push_body_count_spform_005fform_005f0[0]-- > 0)
            out = _jspx_page_context.popBody();
          _jspx_th_spform_005fform_005f0.doCatch(_jspx_exception);
        } finally {
          _jspx_th_spform_005fform_005f0.doFinally();
        }
        _005fjspx_005ftagPool_005fspform_005fform_0026_005fmodelAttribute_005fmethod_005fclass_005faction.reuse(_jspx_th_spform_005fform_005f0);
        _jspx_th_spform_005fform_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spform_005fform_005f0, _jsp_getInstanceManager(), _jspx_th_spform_005fform_005f0_reused);
      }
      out.write("\n");
      out.write("    <table class=\"pure-table pure-table-bordered\">\n");
      out.write("    	<thead>\n");
      out.write("    		<tr>\n");
      out.write("    			<th>index</th>\n");
      out.write("    			<th>stock</th>\n");
      out.write("    		</tr>\n");
      out.write("    	</thead>\n");
      out.write("    	<tbody>\n");
      out.write("    		");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("    	</tbody>\n");
      out.write("    </table>\n");
      out.write("    \n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_spform_005finput_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_spform_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_spform_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spform:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_spform_005finput_005f0 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fspform_005finput_0026_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    boolean _jspx_th_spform_005finput_005f0_reused = false;
    try {
      _jspx_th_spform_005finput_005f0.setPageContext(_jspx_page_context);
      _jspx_th_spform_005finput_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spform_005fform_005f0);
      // /WEB-INF/views/case04/stock.jsp(32,6) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spform_005finput_005f0.setPath("symbol");
      int[] _jspx_push_body_count_spform_005finput_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_spform_005finput_005f0 = _jspx_th_spform_005finput_005f0.doStartTag();
        if (_jspx_th_spform_005finput_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spform_005finput_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spform_005finput_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spform_005finput_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fspform_005finput_0026_005fpath_005fnobody.reuse(_jspx_th_spform_005finput_005f0);
      _jspx_th_spform_005finput_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spform_005finput_005f0, _jsp_getInstanceManager(), _jspx_th_spform_005finput_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spform_005finput_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_spform_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_spform_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spform:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_spform_005finput_005f1 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fspform_005finput_0026_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    boolean _jspx_th_spform_005finput_005f1_reused = false;
    try {
      _jspx_th_spform_005finput_005f1.setPageContext(_jspx_page_context);
      _jspx_th_spform_005finput_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spform_005fform_005f0);
      // /WEB-INF/views/case04/stock.jsp(34,9) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spform_005finput_005f1.setPath("price");
      int[] _jspx_push_body_count_spform_005finput_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_spform_005finput_005f1 = _jspx_th_spform_005finput_005f1.doStartTag();
        if (_jspx_th_spform_005finput_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spform_005finput_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spform_005finput_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spform_005finput_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fspform_005finput_0026_005fpath_005fnobody.reuse(_jspx_th_spform_005finput_005f1);
      _jspx_th_spform_005finput_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spform_005finput_005f1, _jsp_getInstanceManager(), _jspx_th_spform_005finput_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spform_005finput_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_spform_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_spform_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spform:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_spform_005finput_005f2 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fspform_005finput_0026_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    boolean _jspx_th_spform_005finput_005f2_reused = false;
    try {
      _jspx_th_spform_005finput_005f2.setPageContext(_jspx_page_context);
      _jspx_th_spform_005finput_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spform_005fform_005f0);
      // /WEB-INF/views/case04/stock.jsp(36,9) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spform_005finput_005f2.setPath("amount");
      int[] _jspx_push_body_count_spform_005finput_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_spform_005finput_005f2 = _jspx_th_spform_005finput_005f2.doStartTag();
        if (_jspx_th_spform_005finput_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spform_005finput_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spform_005finput_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spform_005finput_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fspform_005finput_0026_005fpath_005fnobody.reuse(_jspx_th_spform_005finput_005f2);
      _jspx_th_spform_005finput_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spform_005finput_005f2, _jsp_getInstanceManager(), _jspx_th_spform_005finput_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/case04/stock.jsp(51,6) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVarStatus("status");
      // /WEB-INF/views/case04/stock.jsp(51,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("stock");
      // /WEB-INF/views/case04/stock.jsp(51,6) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/case04/stock.jsp(51,6) '${ stocks }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${ stocks }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("    		<tr>\n");
            out.write("    			<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ status.index }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("    			<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ stock }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("    		</tr>\n");
            out.write("    		");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
